config/routes.rb
Omrails::Application.routes.draw do
  resources :pinns

  resources :pins

  devise_for :views

  devise_for :users

  get 'about' => 'page#about'

  root :to => 'page#home'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/pinn.rb
class Pinn < ActiveRecord::Base
  attr_accessible :description, :image

  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
  										content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] }			
  										size: { less_than: 5.megabytes }
  belongs_to :user
  has_attached_file :image
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :pinns
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pinns_controller.rb
class PinnsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /pinns
  # GET /pinns.json
  def index
    @pinns = Pinn.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pinns }
    end
  end

  # GET /pinns/1
  # GET /pinns/1.json
  def show
    @pinn = Pinn.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pinn }
    end
  end

  # GET /pinns/new
  # GET /pinns/new.json
  def new
    @pinn = current_user.pinns.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pinn }
    end
  end

  # GET /pinns/1/edit
  def edit
    @pinn = current_user.find(params[:id])
  end

  # POST /pinns
  # POST /pinns.json
  def create
    @pinn = current_user.pinns.new(params[:pinn])

    respond_to do |format|
      if @pinn.save
        format.html { redirect_to @pinn, notice: 'Pinn was successfully created.' }
        format.json { render json: @pinn, status: :created, location: @pinn }
      else
        format.html { render action: "new" }
        format.json { render json: @pinn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pinns/1
  # PUT /pinns/1.json
  def update
    @pinn = current_user.find(params[:id])

    respond_to do |format|
      if @pinn.update_attributes(params[:pinn])
        format.html { redirect_to @pinn, notice: 'Pinn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pinn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pinns/1
  # DELETE /pinns/1.json
  def destroy
    @pinn = current_user.find(params[:id])
    @pinn.destroy

    respond_to do |format|
      format.html { redirect_to pinns_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = Pin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = Pin.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pinns_helper.rb
module PinnsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "Nikita Zhilin", "http://google.com" %>
		By Nikita Zhilin	
	</small>	
</div>	

app/views/layouts/_header.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
            <%= link_to "One Month Rails", root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
	         <li><%= link_to "Home", root_path %></li>
			     <li><%= link_to "About", about_path %></li>
		    </ul>	
		<ul class="nav pull-right">
          <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	        <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
          <%else %>
          <li><%= link_to "Login", new_user_session_path  %></li>
          <%end%>
		</ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>	
			<%= yield %>
			<%= render 'layouts/footer' %>	
		</div>	
	</body>
</html>

app/views/page/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "One Month Rails", "http://onemorelink.org" %>
	Is a project to teach
	<%= link_to "Ruby on Rails", "http://onemorelink2.org" %>

</p>

app/views/page/home.html.erb
<% if user_signed_in? %>
	<h1> You're logged in </h1>
<%else%>	

<div class="hero-unit">
	<h1>Welcome to One Month Rails!</h1>
		<p>
			You've found the home page for the
			<%= link_to "One Month Rails", "http://onemonthrails.com" %>
			application
		</p>
		<p>
			<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn large" %>
		</p>
</div>
<%end%>

app/views/pinns/_form.html.erb
<%= simple_form_for(@pinn, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description, as: :text, input_html: {rows: "3"} %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pinns/_pinn.html.erb
<tr>
  <td><%= pinn.description %></td>
  <td><%= link_to 'Show', pinn %></td>
  <% if current_user == pinn.user %>
	  <td><%= link_to 'Edit', edit_pinn_path(pinn) %></td>
	  <td><%= link_to 'Destroy', pinn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  <% end %>
</tr>

app/views/pinns/edit.html.erb
<h1>Editing pinn</h1>

<%= render 'form' %>

<%= link_to 'Show', @pinn %> |
<%= link_to 'Back', pinns_path %>

app/views/pinns/index.html.erb
<h1>Listing pinns</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @pinns %>
  </tbody>
</table>

<br />

<%= link_to 'New Pinn', new_pinn_path %>

app/views/pinns/new.html.erb
<h1>New pinn</h1>

<%= render 'form' %>

<%= link_to 'Back', pinns_path %>

app/views/pinns/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
			   <%= @pinn.description %>
			</p>
			<p>
			   <%= @pinn.user.name %>
			</p>
			<% if current_user == @pinn.user %>
			<%= link_to 'Edit', edit_pinn_path(@pinn) %> | <% end %>
			<%= link_to 'Back', pinns_path %>
		</div>	
	</div>
</div>		

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pins.each do |pin| %>
  <tr>
    <td><%= link_to 'Show', pin %></td>
    <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
    <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>